# config-management.yaml
apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
spec:
  clusterName: demo-test-cluster
  git:
    syncRepo: https://github.com/munnerz/csp-defaulting-demo-repo.git
    syncBranch: master
    secretType: none